# Generated by Django 5.0.6 on 2024-06-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now=True)),
                ('profile_picture', models.ImageField(upload_to='user_management/profile_pictures')),
                ('preferred_language', models.CharField(default='english', max_length=16)),
                ('subscription_status', models.CharField(default='free', max_length=16)),
            ],
        ),
    ]
