# Generated by Django 5.0.6 on 2024-06-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('criteria', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateField(auto_now=True)),
                ('achievement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.achievements')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.users')),
            ],
        ),
    ]
